# 1) Ensure the following environmental variables are set
# - DB_PASSWORD
# - ADMIN_PASSWORD
# - SECRET_KEY
# - EMAIL_PASSWORD
#
# 2) Ensure you have a config.yaml defined in the same directory as this docker-compose.yaml file.
# 3) Run `docker-compose up`.
version: '3.4'

x-gavel-base: &gavel_base
  image: ghcr.io/hacktheu-org/gavel/gavel:latest
  restart: always
  volumes:
    # Config file for Gavel to consume.
    - ./config.yaml:/opt/gavel/config.yaml
  networks:
    - gavel-net
  environment:
    REDIS_URL: redis://redis/0
    DATABASE_URL: postgresql://gavel:${DB_PASSWORD:?must set the DB_PASSWORD environment variable}@db/gavel
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    SECRET_KEY: ${SECRET_KEY}
    EMAIL_PASSWORD: ${EMAIL_PASSWORD}

services:
  gavel:
    <<: *gavel_base
    ports:
      - 80:80
    depends_on:
      - db
      - redis

  celery-worker:
    <<: *gavel_base
    depends_on:
      - gavel
    command: celery -A gavel:celery worker

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gavel
      POSTGRES_PASSWORD: ${DB_PASSWORD:?must set the DB_PASSWORD environment variable}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - gavel-net

  redis:
    image: redis
    restart: always
    networks:
      - gavel-net

networks:
  gavel-net:
